server:
  listen: 127.0.0.1:18000
  listenPeer: 127.0.0.1:18000
  gracefullStopTimeout: 1s
  checkRedisTypologyTicker: 10s
input:
  redis:
    addresses: [127.0.0.1:16300,127.0.0.1:16301]
    type: cluster
  mode: dynamic
  syncDelayTestKey: redis-GunYu-syncDelay-testKey
  syncFrom: prefer_slave
channel:
  storer:
    dirPath: /tmp/redisgunyu-cluster
    maxSize: 209715200
    logSize: 20971520
  staleCheckpointDuration: 10m
output:
  redis:
    addresses: [127.0.0.1:16400,127.0.0.1:16401]
    type: cluster
  replay:
    resumeFromBreakPoint: true
    keyExists: replace
    metric: true
    targetDb: -1
    replayTransaction: true
log:
  level: info
  handler:
    stdout: true
  withCaller: false
  withFunc: false
cluster:
  groupName: redis1
  leaseTimeout: 9s
  # metaEtcd: 
  #   endpoints:
  #     - 127.0.0.1:2379